apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  namespace: weather
spec:
  selector:
    app: web-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer