AWSTemplateFormatVersion: 2010-09-09

Resources:
  EC2NginxInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0245697ee3e07e755
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: NginxServerCloud

      
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo apt-get -y update
            sudo apt-get -y install nginx
            cd /var/www
            chgrp ec2-user html
            chown ec2-user html
            cd html

            cat <<EOF > index.html
            <!DOCTYPE html>
            <html>
            <body>
            <center>
            <h1>Hello world from Crash course DevOps!</h1>
            </center>
            </body>
            </html>
            EOF

            sudo systemctl start nginx
      SecurityGroups:
        - !Ref NginxSecurityGroup
  
  NginxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Nginx Security Group
      GroupName: NginxSG

      SecurityGroupIngress:
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80 

        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22 